### ISSUE TITLE
ACTION is not displayed correctly

### ISSUE THREAD

**Issue by derixithy** [c00kiemon5ter/iim#3]
When i get an action on a channel it display like this:
[w]ACTION grabs a peace of wood out of the forrest [w]

* [w] Is the character you refer to as a BEL

It should display as:
* grabs a peace of wood out of the forrest *

**Comment by c00kiemon5ter** [comment]
hi and thanks for using `iim`. 

`ACTION` is a `CTCP` message. `CTCP` messages have the following format: 

```
PRIVMSG <target>:^A<command> <data>^A
```

`iim` itself does not process `CTCP` messages, thus you get the whole ACTION string. 
This is left for the frontends to handle, like [`iii`](https://github.com/c00kiemon5ter/iii) does [here](https://github.com/c00kiemon5ter/iii/blob/master/iii.sh#L77)

I was planning to rewrite `iim` to do even less - just connect to the IRC server and write and 
send raw messages. On top of it, `iii` would be rewritten to do all the needed string processing
and manipulation so that messages are displayed and sent as supposed to. Still thinking about
the whole design and how the different parts should communicate - separate the responsibilities
of each..
However I got caught up by work and haven't found the time to do that.

**Comment by derixithy** [comment]
I thought it was strange behavior to get the escape character in the output file.
I already have a bash script that will strip this and even allow to send me ACTION messages.

This is the code i use if you are interested:
```
echo -ne "/r PRIVMSG $channel :\x01ACTION${line#/me }\x01\r\n" > "$cache/$server/in"
```

Thanks for the swift reply
