### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by derixithy** [c00kiemon5ter/iim#6]
Is there support for ssl because i could not find it or could this be added?

**Comment by c00kiemon5ter** [comment]
SSL/TLS support has been left out due to complexity. 
It is recommended to use [stunnel](https://www.stunnel.org/downloads.html), [tlstunnel](https://github.com/hannesm/tlstunnel) or [hitch](https://github.com/varnish/hitch) 
(not [stud](https://github.com/bumptech/stud) which is now abandonware). 

That way the complexity and issues and dependencies that come 
with SSL/TLS are isolated to a separate layer/program build to 
specifically address and support that problem.

**Comment by c00kiemon5ter** [comment]
I am using stunnel but I've been meaning to try the other tools as well. 

An example config would be the following

```
CApath = /etc/ssl/certs

foreground = yes
output = /dev/stdout
pid =
setuid = USERNAME

[freenode]
accept  = freenode:6667
connect = chat.freenode.net:6697
client  = yes
retry   = yes
verify  = 2
```

As you've noted I let it run in the foreground along with other stuff in a dedicated tmux pane.
Do not forget to change `USERNAME` to your user. 

With that in place start stunnel as

```
stunnel4 ~/.stunnel/stunnel.conf
```

and then connect to host `127.0.0.1` and port `6667`

Another trick you can do is add an entry in `/etc/hosts` like so

```
127.0.0.1 freenode
```

and then connect to host `freenode` and port `6667`

As a result all connections go through stunnel which setups and verifies the SSL/TLS certificate for freenode (or any other host you setup) and SSL/TLS support is now available ;)

**Comment by derixithy** [comment]
Thank you, this answered my question perfectly.
